title: jasinobe
description: blog
author: Jasmeet Oberai

email: joberai@uwaterloo.ca
github: jasmeeto
linkedin: jasoberai
facebook: jas.oberai
twitter: JasmeetOberai

name: jasinobe
highlighter: pygments