jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
            cache-path: ~/project/node_modules
      - run:
          command: npm run build
      - run: |
          git config --global -l
          git config --global user.email circleci@circleci
          git config --global user.name CircleCI
      - run:
          command: npm run deploy
version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - build-and-deploy